[phases.setup]
nixPkgs = ['python310', 'pip']

[phases.install]
cmds = ['python3 -m pip install --upgrade pip', 'pip install -r requirements.txt']

[start]
cmd = 'gunicorn run:app --host=0.0.0.0 --port=$PORT'